# Generated by Django 5.0.4 on 2024-04-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App01Menus', '0002_producto_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
            ],
        ),
    ]
